package Collection_Framework.Streams.Stream;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Stream;

public class ParalleStream {
    public static void main(String[] args) {
        // A type of stream that enables parallel processing of elements
        // Allowing multiple threads to process parts of the stream simultaneously
        // This can significantly improve performance for large data sets
        // workload is distributed across multiple threads

        long start = System.currentTimeMillis();
        List<Integer> list = Stream.iterate(1, x -> x + 1).limit(20000).toList();
        List<Long> factList = list.stream().map(n -> factorial(n)).toList();
        long end = System.currentTimeMillis();
        System.out.println("Time taken with stream " + (end - start) + " ms");

        // use parallel stream
        long startTime = System.currentTimeMillis();
        List<Integer> list1 = Stream.iterate(1, x -> x + 1).limit(20000).toList();
        List<Long> factListParallel = list1.parallelStream().map(n -> factorial(n)).toList();
        long endTime = System.currentTimeMillis();
        System.out.println("Time taken with parallel stream " + (endTime - startTime) + " ms");
        
        
        // Parallel streams are most effective for CPU-intensive or large datasets where tasks are 
        // independent (like factorial, not cumulative sum)
        // They may add for simple tasks or small datasets
        
        // Cumulative Sum
        // [1 2 3 4 5] --> [1 3 6 10 15]
        List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5);
        AtomicInteger sum = new AtomicInteger(0);
        List<Integer> cumSum = numbers.parallelStream().map(x -> sum.addAndGet(x)
//            int i = x + sum; // err : local variables referenced from a lambda expression must be final or effectively final
//            sum = i;
//            return i;

        ).toList();
        // how can we change sum if it is final
        // To achieve thread safety we use AtomicInteger
        // addAndGet(x) adds the given value to the current value
        // but the result will be inconsistent
        System.out.println("Expected cumulative sum: [1, 3, 6, 10, 15 ]");
        System.out.println("Actual result with parallel stream: " + cumSum);


        // sequential() method
        // if calculating cumulative sum of factorial list which is generated by parallelStream
        // sequential method converts parallel stream into sequential stream
        // we can get consistent result(cumulative sum).

        List<Long> factListSeq = numbers.parallelStream().map(ParalleStream::factorial).sequential().toList();


    }

    private static long factorial(int n){
        long result = 1;
        for(int i = 2; i <= n; i++){
            result *= i;
        }
        return result;
    }
}
